development:
  adapter: postgresql
  encoding: unicode
  database: book-club_development
  pool: 5
  username:
  password:


test:
  adapter: postgresql
  encoding: unicode
  database: book-club_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: book-club_production
  pool: 5
  username:
  password:
